from fastapi.testclient import TestClient

from app.main import create_app


def test_health_check_returns_ok() -> None:
    client = TestClient(create_app())

    response = client.get("/health")

    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_core_platform_routes_are_registered() -> None:
    app = create_app()
    paths = {getattr(route, "path", "") for route in app.routes}

    expected = {
        "/api/v1/sessions",
        "/api/v1/sessions/{session_id}",
        "/api/v1/sessions/revoke-others",
        "/api/v1/auth/register",
        "/api/v1/user-profile/me",
        "/api/v1/auth/me",
        "/api/v1/users",
        "/api/v1/users/{user_id}",
        "/api/v1/rbac/permissions",
        "/api/v1/rbac/roles",
        "/api/v1/rbac/roles/{role_id}",
        "/api/v1/rbac/assignments",
        "/api/v1/rbac/assignments/{user_id}/{role_id}",
        "/api/v1/admin/overview",
        "/api/v1/organizations",
        "/api/v1/organizations/{org_id}",
        "/api/v1/tenants",
        "/api/v1/mssp/console",
        "/api/v1/mssp/overview",
        "/api/v1/customer-portal/summary",
        "/api/v1/branding/current",
        "/api/v1/licenses/current",
        "/api/v1/usage/current",
        "/api/v1/usage/record",
        "/api/v1/billing/account",
        "/api/v1/billing/invoices",
        "/api/v1/system-settings/current",
        "/api/v1/ingest/health",
        "/api/v1/ingest/capabilities",
        "/api/v1/ingest/queue",
        "/api/v1/ingest/dead-letter",
        "/api/v1/ingest/rate-limits",
        "/api/v1/ingest/auth/status",
        "/api/v1/ingest/rest",
        "/api/v1/ingest/batch-upload",
        "/api/v1/ingest/webhook/{source}",
        "/api/v1/ingest/malformed",
        "/api/v1/ingest/deduplicate/check",
        "/api/v1/parsing/capabilities",
        "/api/v1/parsing/parsers",
        "/api/v1/parsing/mappings",
        "/api/v1/parsing/test",
        "/api/v1/parsing/pipeline/run",
        "/api/v1/parsing/normalize",
        "/api/v1/parsing/failures",
        "/api/v1/enrichment/capabilities",
        "/api/v1/enrichment/identity/lookup",
        "/api/v1/enrichment/asn/lookup",
        "/api/v1/enrichment/dns/reverse",
        "/api/v1/enrichment/threat-intel/lookup",
        "/api/v1/enrichment/vulnerabilities/context",
        "/api/v1/enrichment/cloud/context",
        "/api/v1/enrichment/mitre/context",
        "/api/v1/enrichment/kill-chain/context",
        "/api/v1/storage/capabilities",
        "/api/v1/storage/tiers",
        "/api/v1/storage/tiering-policy",
        "/api/v1/storage/retention-policy",
        "/api/v1/storage/indexing",
        "/api/v1/storage/usage",
        "/api/v1/storage/optimization",
        "/api/v1/storage/sampling-policy",
        "/api/v1/storage/pre-ingestion-filter",
        "/api/v1/storage/cost-control",
        "/api/v1/search/capabilities",
        "/api/v1/search/query/parse",
        "/api/v1/search/query/translate",
        "/api/v1/search/ai/generate",
        "/api/v1/search/ai/explain",
        "/api/v1/search/saved",
        "/api/v1/search/scheduled",
        "/api/v1/search/history",
        "/api/v1/search/templates",
        "/api/v1/search/performance",
        "/api/v1/search/permissions",
        "/api/v1/search/federated/status",
        "/api/v1/search/archive/status",
        "/api/v1/search/export/json",
        "/api/v1/search/export/csv",
        "/api/v1/search/export/pdf",
        "/api/v1/detection/capabilities",
        "/api/v1/detection/rules/import/sigma",
        "/api/v1/detection/rules/{rule_id}/export/sigma",
        "/api/v1/detection/rules/convert/sigma",
        "/api/v1/detection/rules/custom/validate",
        "/api/v1/detection/threshold/preview",
        "/api/v1/detection/correlation/preview",
        "/api/v1/detection/sequence/preview",
        "/api/v1/detection/statistical/preview",
        "/api/v1/detection/anomaly/preview",
        "/api/v1/detection/ml/preview",
        "/api/v1/detection/behavioral/preview",
        "/api/v1/detection/hunt/query",
        "/api/v1/detection/simulate",
        "/api/v1/detection/benchmark",
        "/api/v1/detection/rules/{rule_id}/versions",
        "/api/v1/detection/dac/status",
        "/api/v1/detection/git/status",
        "/api/v1/detection/rules/{rule_id}/approval",
        "/api/v1/detection/coverage/gaps",
        "/api/v1/detection/mitre/map",
        "/api/v1/detection/mitre/coverage",
        "/api/v1/detection/kill-chain/map",
        "/api/v1/detection/false-positive/analytics",
        "/api/v1/alerts/capabilities",
        "/api/v1/alerts/generate/preview",
        "/api/v1/alerts/severity/model",
        "/api/v1/alerts/risk/score",
        "/api/v1/alerts/risk-based/policy",
        "/api/v1/alerts/deduplication/preview",
        "/api/v1/alerts/grouping/preview",
        "/api/v1/alerts/suppression/policies",
        "/api/v1/alerts/escalation/policies",
        "/api/v1/alerts/notifications/preview",
        "/api/v1/alerts/tuning/recommendations",
        "/api/v1/alerts/noise-reduction/summary",
        "/api/v1/alerts/priority-queue",
        "/api/v1/alerts/review-queue",
        "/api/v1/alerts/{alert_id}/comments",
        "/api/v1/alerts/{alert_id}/sla",
        "/api/v1/alerts/{alert_id}/evidence",
        "/api/v1/alerts/{alert_id}/timeline",
        "/api/v1/alerts/{alert_id}/audit-trail",
        "/api/v1/alerts/{alert_id}/review",
        "/api/v1/incidents/capabilities",
        "/api/v1/incidents/severity/model",
        "/api/v1/incidents",
        "/api/v1/incidents/{incident_id}",
        "/api/v1/incidents/{incident_id}/alerts",
        "/api/v1/incidents/{incident_id}/timeline",
        "/api/v1/incidents/{incident_id}/notes",
        "/api/v1/incidents/{incident_id}/kill-chain-timeline",
        "/api/v1/incidents/{incident_id}/evidence",
        "/api/v1/incidents/{incident_id}/chain-of-custody",
        "/api/v1/incidents/{incident_id}/root-cause",
        "/api/v1/incidents/{incident_id}/affected-assets",
        "/api/v1/incidents/{incident_id}/affected-users",
        "/api/v1/incidents/{incident_id}/iocs",
        "/api/v1/incidents/{incident_id}/collaboration",
        "/api/v1/incidents/{incident_id}/post-incident-review",
        "/api/v1/incidents/{incident_id}/report",
        "/api/v1/incidents/{incident_id}/executive-summary",
        "/api/v1/incidents/{incident_id}/closure",
        "/api/v1/cases",
        "/api/v1/cases/{case_id}",
        "/api/v1/ai/alerts/summarize",
        "/api/v1/ai/alerts/triage",
        "/api/v1/ai/severity/recommend",
        "/api/v1/ai/false-positive/score",
        "/api/v1/ai/investigation/assistant",
        "/api/v1/ai/root-cause",
        "/api/v1/ai/timeline/generate",
        "/api/v1/ai/threat-hunting/assistant",
        "/api/v1/ai/detection/rule/generate",
        "/api/v1/ai/detection/sigma/generate",
        "/api/v1/ai/query/generate",
        "/api/v1/ai/query/optimize",
        "/api/v1/ai/query/explain",
        "/api/v1/ai/report/write",
        "/api/v1/ai/executive-summary",
        "/api/v1/ai/compliance-report",
        "/api/v1/ai/playbook/build",
        "/api/v1/ai/runbook/assist",
        "/api/v1/ai/noise-reduction",
        "/api/v1/ai/correlation/recommend",
        "/api/v1/ai/evidence/citations",
        "/api/v1/ai/hallucination/check",
        "/api/v1/ai/prompt-audit/logs",
        "/api/v1/ai/guardrails/policy",
        "/api/v1/ai/privacy/redaction/preview",
        "/api/v1/ai/models/selection",
        "/api/v1/ai/providers/local/status",
        "/api/v1/ai/providers/cloud/status",
        "/api/v1/ai/rag/query",
        "/api/v1/ai/knowledge-base/articles",
        "/api/v1/ai/knowledge-base/search",
        "/api/v1/assets",
        "/api/v1/assets/{asset_id}",
        "/api/v1/assets/{asset_id}/risk",
        "/api/v1/assets/capabilities",
        "/api/v1/assets/inventory/summary",
        "/api/v1/assets/risk/model",
        "/api/v1/assets/risk/score",
        "/api/v1/assets/ownership/policy",
        "/api/v1/assets/tagging/preview",
        "/api/v1/assets/criticality/model",
        "/api/v1/assets/criticality/score",
        "/api/v1/assets/discovery/preview",
        "/api/v1/assets/discovery/cloud",
        "/api/v1/assets/discovery/attack-surface",
        "/api/v1/identity/capabilities",
        "/api/v1/identity/users/inventory",
        "/api/v1/identity/inventory",
        "/api/v1/identity/integrations/active-directory/status",
        "/api/v1/identity/integrations/ldap/status",
        "/api/v1/identity/integrations/entra/status",
        "/api/v1/identity/integrations/okta/status",
        "/api/v1/identity/integrations/cloud/status",
        "/api/v1/identity/privileged-accounts/monitor",
        "/api/v1/identity/service-accounts/monitor",
        "/api/v1/identity/iam-risk/score",
        "/api/v1/identity/ueba/user-behavior",
        "/api/v1/identity/ueba/entity-behavior",
        "/api/v1/identity/ueba/baseline",
        "/api/v1/identity/ueba/peer-groups",
        "/api/v1/identity/detections/impossible-travel",
        "/api/v1/identity/detections/mfa-fatigue",
        "/api/v1/identity/detections/password-spraying",
        "/api/v1/threat-intel/capabilities",
        "/api/v1/threat-intel/feeds",
        "/api/v1/threat-intel/iocs",
        "/api/v1/threat-intel/iocs/match",
        "/api/v1/threat-intel/iocs/expiry",
        "/api/v1/threat-intel/iocs/confidence/score",
        "/api/v1/threat-intel/reputation/ip",
        "/api/v1/threat-intel/reputation/domain",
        "/api/v1/threat-intel/reputation/url",
        "/api/v1/threat-intel/reputation/hash",
        "/api/v1/threat-intel/reputation/email",
        "/api/v1/threat-intel/integrations/misp/status",
        "/api/v1/threat-intel/integrations/virustotal/status",
        "/api/v1/threat-intel/integrations/abuseipdb/status",
        "/api/v1/threat-intel/integrations/otx/status",
        "/api/v1/threat-intel/integrations/stix-taxii/status",
        "/api/v1/threat-intel/feeds/deduplicate",
        "/api/v1/threat-intel/actors",
        "/api/v1/threat-intel/malware-families",
        "/api/v1/threat-intel/campaigns",
        "/api/v1/threat-intel/dashboard",
        "/api/v1/soar/capabilities",
        "/api/v1/soar/playbooks",
        "/api/v1/soar/playbooks/builder/preview",
        "/api/v1/soar/playbooks/test",
        "/api/v1/soar/actions/manual",
        "/api/v1/soar/actions/automated",
        "/api/v1/soar/approvals",
        "/api/v1/soar/actions/webhook/preview",
        "/api/v1/soar/notifications/email/preview",
        "/api/v1/soar/notifications/slack/preview",
        "/api/v1/soar/notifications/teams/preview",
        "/api/v1/soar/tickets/preview",
        "/api/v1/soar/integrations/jira/status",
        "/api/v1/soar/integrations/servicenow/status",
        "/api/v1/soar/exports/firewall-blocklist",
        "/api/v1/soar/integrations/edr/status",
        "/api/v1/soar/actions/endpoint-isolation/preview",
        "/api/v1/soar/actions/user-disable/preview",
        "/api/v1/soar/actions/password-reset/preview",
        "/api/v1/soar/actions/ip-block/preview",
        "/api/v1/soar/actions/domain-block/preview",
        "/api/v1/soar/actions/host-quarantine/preview",
        "/api/v1/soar/audit-log",
        "/api/v1/soar/safety-controls",
        "/api/v1/soar/rate-limits",
        "/api/v1/soar/rollback/preview",
        "/api/v1/security-analytics/capabilities",
        "/api/v1/security-analytics/authentication",
        "/api/v1/security-analytics/powershell",
        "/api/v1/security-analytics/process-tree",
        "/api/v1/security-analytics/file-integrity",
        "/api/v1/security-analytics/registry",
        "/api/v1/security-analytics/usb",
        "/api/v1/security-analytics/remote-access",
        "/api/v1/security-analytics/vpn",
        "/api/v1/security-analytics/dns-query",
        "/api/v1/security-analytics/network-flow",
        "/api/v1/security-analytics/packet-metadata",
        "/api/v1/security-analytics/waf",
        "/api/v1/security-analytics/web-attack",
        "/api/v1/security-analytics/database-attack",
        "/api/v1/security-analytics/cloud-misconfiguration",
        "/api/v1/security-analytics/lateral-movement",
        "/api/v1/security-analytics/privilege-escalation",
        "/api/v1/security-analytics/data-exfiltration",
        "/api/v1/security-analytics/ransomware",
        "/api/v1/security-analytics/command-control",
        "/api/v1/security-analytics/insider-threat",
        "/api/v1/security-analytics/malware-behavior",
        "/api/v1/security-analytics/credential-theft",
        "/api/v1/security-analytics/persistence",
        "/api/v1/security-analytics/defense-evasion",
        "/api/v1/security-analytics/cloud/aws",
        "/api/v1/security-analytics/cloud/azure",
        "/api/v1/security-analytics/cloud/gcp",
        "/api/v1/security-analytics/cloudtrail",
        "/api/v1/audit/logs",
        "/api/v1/audit/logs/export",
        "/api/v1/audit/logs/{audit_id}",
        "/api/v1/agents/enroll",
        "/api/v1/agents/authenticate",
        "/api/v1/agents/{agent_id:uuid}/mtls",
        "/api/v1/agents/{agent_id:uuid}/zero-trust",
        "/api/v1/agents/policy-groups",
        "/api/v1/agents/policy-groups/{group_id}",
        "/api/v1/agents/{agent_id:uuid}/config",
        "/api/v1/agents/{agent_id:uuid}/heartbeat/v2",
        "/api/v1/agents/{agent_id:uuid}/health",
        "/api/v1/agents/status/dashboard",
        "/api/v1/agents/{agent_id:uuid}/self-update",
        "/api/v1/agents/{agent_id:uuid}/tamper-protection",
        "/api/v1/agents/{agent_id:uuid}/tamper-events",
        "/api/v1/agents/{agent_id:uuid}/offline-buffer",
        "/api/v1/agents/{agent_id:uuid}/offline-replay",
        "/api/v1/agents/{agent_id:uuid}/throttling",
        "/api/v1/agents/{agent_id:uuid}/compression",
        "/api/v1/agents/{agent_id:uuid}/encryption",
        "/api/v1/agents/{agent_id:uuid}/local-parsing",
        "/api/v1/agents/{agent_id:uuid}/local-filtering",
        "/api/v1/agents/{agent_id:uuid}/sensitive-data-masking",
        "/api/v1/agents/plugins",
        "/api/v1/agents/{agent_id:uuid}/plugins",
        "/api/v1/agents/{agent_id:uuid}/plugins/{plugin_name}",
        "/api/v1/agents/forwarders/windows",
        "/api/v1/agents/{agent_id:uuid}/forwarders/windows",
        "/api/v1/agents/forwarders/linux",
        "/api/v1/agents/{agent_id:uuid}/forwarders/linux",
        "/api/v1/agents/forwarders/macos",
        "/api/v1/agents/{agent_id:uuid}/forwarders/macos",
        "/api/v1/agents/forwarders/containers",
        "/api/v1/agents/{agent_id:uuid}/forwarders/containers",
        "/api/v1/agents/forwarders/kubernetes",
        "/api/v1/agents/{agent_id:uuid}/forwarders/kubernetes",
        "/api/v1/agents/collectors/windows-event-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/windows-event-log",
        "/api/v1/agents/collectors/windows-security-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/windows-security-log",
        "/api/v1/agents/collectors/windows-system-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/windows-system-log",
        "/api/v1/agents/collectors/windows-application-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/windows-application-log",
        "/api/v1/agents/collectors/powershell-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/powershell-log",
        "/api/v1/agents/collectors/sysmon-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/sysmon-log",
        "/api/v1/agents/collectors/linux-file-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/linux-file-log",
        "/api/v1/agents/collectors/linux-auth-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/linux-auth-log",
        "/api/v1/agents/collectors/linux-syslog",
        "/api/v1/agents/{agent_id:uuid}/collectors/linux-syslog",
        "/api/v1/agents/collectors/linux-auditd",
        "/api/v1/agents/{agent_id:uuid}/collectors/linux-auditd",
        "/api/v1/agents/collectors/linux-journald",
        "/api/v1/agents/{agent_id:uuid}/collectors/linux-journald",
        "/api/v1/agents/collectors/apache-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/apache-log",
        "/api/v1/agents/collectors/nginx-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/nginx-log",
        "/api/v1/agents/collectors/iis-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/iis-log",
        "/api/v1/agents/collectors/database-audit-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/database-audit-log",
        "/api/v1/agents/collectors/docker-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/docker-log",
        "/api/v1/agents/collectors/kubernetes-audit-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/kubernetes-audit-log",
        "/api/v1/agents/collectors/cloudtrail",
        "/api/v1/agents/{agent_id:uuid}/collectors/cloudtrail",
        "/api/v1/agents/collectors/azure-activity-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/azure-activity-log",
        "/api/v1/agents/collectors/google-cloud-audit-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/google-cloud-audit-log",
        "/api/v1/agents/collectors/firewall-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/firewall-log",
        "/api/v1/agents/collectors/proxy-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/proxy-log",
        "/api/v1/agents/collectors/vpn-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/vpn-log",
        "/api/v1/agents/collectors/dns-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/dns-log",
        "/api/v1/agents/collectors/dhcp-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/dhcp-log",
        "/api/v1/agents/collectors/waf-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/waf-log",
        "/api/v1/agents/collectors/email-security-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/email-security-log",
        "/api/v1/agents/collectors/edr-xdr-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/edr-xdr-log",
        "/api/v1/agents/collectors/application-security-log",
        "/api/v1/agents/{agent_id:uuid}/collectors/application-security-log",
        "/api/v1/agents/collectors/custom-file",
        "/api/v1/agents/{agent_id:uuid}/collectors/custom-file",
    }

    assert expected.issubset(paths)


def test_incident_workflow_routes_support_expected_methods() -> None:
    app = create_app()
    route_methods = {}
    for route in app.routes:
        path = getattr(route, "path", "")
        methods = getattr(route, "methods", set())
        route_methods.setdefault(path, set()).update(methods)

    assert {"GET", "POST"}.issubset(route_methods["/api/v1/incidents"])
    assert {"GET", "PUT", "PATCH", "DELETE"}.issubset(route_methods["/api/v1/incidents/{incident_id}"])
    assert {"POST"}.issubset(route_methods["/api/v1/incidents/{incident_id}/alerts"])
    assert {"GET", "POST"}.issubset(route_methods["/api/v1/incidents/{incident_id}/timeline"])


def test_audit_routes_support_expected_methods() -> None:
    app = create_app()
    route_methods = {}
    for route in app.routes:
        path = getattr(route, "path", "")
        methods = getattr(route, "methods", set())
        route_methods.setdefault(path, set()).update(methods)

    assert {"GET"}.issubset(route_methods["/api/v1/audit/logs"])
    assert {"GET"}.issubset(route_methods["/api/v1/audit/logs/export"])
    assert {"GET"}.issubset(route_methods["/api/v1/audit/logs/{audit_id}"])
